### ISSUE TITLE
Ability to mock clock movement for a single or desired billing record.

### ISSUE THREAD

**Issue by ludo550** [killbill/killbill-commons#87] opened 2020-10-28 06:11 UTC
Ability to mock clock movement for a single record.
We are trying to test several billing scenarios in our preproduction system. We are trying to parallelize our tests in order to save time. Our constraint is that the clock is global to all the billing records. Would this be a valid request?

**Comment by pierre** [comment] 2020-10-28 06:29
Duplicate of https://github.com/killbill/killbill/issues/294.

Please reach out to the [mailing-list](https://groups.google.com/forum/#!forum/killbilling-users) instead. See [our communication guidelines](https://github.com/killbill/killbill/blob/master/.github/CONTRIBUTING.md).

**Closed by pierre** 2020-10-28 06:29 UTC
Labels: invalid
